ingress:
  enabled: true
  hosts:
    - host: n8n.fabrice.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - hosts:
        - n8n.fabrice.local
      secretName: quickstart-example-tls
